### ISSUE TITLE
Plan COAM usability testing with industry

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/cas-compliance#51]
Once the interregnum is finished, do a round of external usability testing with industry with the COAM wireframes.

- [x] Designers [plan user testing session outline](https://miro.com/app/board/uXjVNU30Ns4=/?moveToWidget=3458764608297438352&cot=14) (what to test, how, session length etc.)
_
- [x] Service designer drafts recruiting email with consent form, peer review/revision
- [x] Service designer identify 5-7 operators/staff to contact, peer review/revision
- [x] Service designer schedule sessions
_
- [x] UX Designer drafts [test scripts](https://bcgov.sharepoint.com/:w:/r/teams/00608-DesignersInternal/_layouts/15/doc2.aspx?sourcedoc=%7B7D7FBE55-46A5-4A47-BC9F-E7F04BC08699%7D&file=Usability%20Testing%20-%20Compliance%20(External).docx&action=default&mobileredirect=true) (intro, task list, questions, ending, etc.), peer review/revision
- [x] UX Designer set up [test link](https://www.figma.com/proto/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?page-id=14307%3A1663&node-id=20107-1497&node-type=frame&viewport=1759%2C-4811%2C0.18&t=R84f08k3URorRHkS-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=20107%3A1497&show-proto-sidebar=1) in Figma

**Comment by NicoleGovvy** [comment]
@nanyangpro thank you for the additions and they all look great to me. I don't have any further questions for this. I will get started on the recruitment list and email text.

**Comment by nanyangpro** [comment]
Thanks @NicoleGovvy for your absolutely amazing planning and efficient scheduling!

I've added link to the scripts and clickable interactive prototype for our upcoming usability testings in the ticket description for reference. Looking forward to the sessions!
