### ISSUE TITLE
Conduct COAM usability testing with industry

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/cas-compliance#52]
According to planning, we are aiming at the week of 6th and 13th for the 5(+) usability testing sessions
- [x] Conduct usability testing sessions and document feedback
- [x] Analyze feedback
- [x] Make recommendations/updates

**Comment by vesselak** [comment]
Usability sessions held on December 11, 12, 16, 17 and 18 (½ of scope) 
Recommendations summarized here [https://bcgov.sharepoint.com/:x:/r/teams/00608-DesignersInternal/_layouts/15/Doc.aspx?sourcedoc=%7BB794A2F0-D69A-450A-8582-EC4220F23F6B%7D&file=Recommendations%20-%20Compliance%20(External).xlsx&action=default&mobileredirect=true](url)
Notes stored here [https://miro.com/app/board/uXjVKnAekjA=/](url)
